export const PRODUCTS = [
  {
    id: 'p1',
    name: 'Butterhead Lettuce',
    price: 79,
    unit: '150g',
    category: 'Leafy',
    badges: ['Pesticide-free', 'Hydroponic'],
    images: ['https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=1200&q=80&auto=format&fit=crop'],
    short_desc: 'Tender heads with a sweet, mellow crunch.',
    long_desc: 'Grown in a controlled hydroponic system for consistent texture and flavor.',
    nutrition: 'Per 100g: 15 kcal',
    storage_tips: 'Refrigerate at 2–4°C',
    farm_location: 'Hyderabad City Farm',
    availability: 'In stock',
    sku: 'UH-LTS-150',
  },
  {
    id: 'p2',
    name: 'Genovese Basil',
    price: 59,
    unit: '50g',
    category: 'Herbs',
    badges: ['Harvested today'],
    images: ['https://images.unsplash.com/photo-1498842812179-c81beecf902c?w=1200&q=80&auto=format&fit=crop'],
    short_desc: 'Aromatic leaves perfect for pesto.',
    long_desc: 'Hydroponic basil with concentrated aroma.',
    nutrition: 'Per 10g: 3 kcal',
    storage_tips: 'Avoid crushing; store loosely.',
    farm_location: 'Gachibowli Pod',
    availability: 'Low stock',
    sku: 'UH-BSL-050',
  },
  {
    id: 'p3',
    name: 'Red Oakleaf Mix',
    price: 89,
    unit: '150g',
    category: 'Leafy',
    badges: ['Hydroponic'],
    images: ['https://images.unsplash.com/photo-1506806732259-39c2d0268443?w=1200&q=80&auto=format&fit=crop'],
    short_desc: 'Delicate leaves with nutty undertones.',
    long_desc: 'A chef-favorite for plating and texture.',
    nutrition: 'Per 100g: 18 kcal',
    storage_tips: 'Use within 3–4 days.',
    farm_location: 'Madhapur Vertical',
    availability: 'In stock',
    sku: 'UH-OKL-150',
  },
  {
    id: 'p4',
    name: 'Microgreens Sampler',
    price: 129,
    unit: '100g',
    category: 'Microgreens',
    badges: ['Nutrient-dense'],
    images: ['https://images.unsplash.com/photo-1593179241555-c2c6d3bda8b1?w=1200&q=80&auto=format&fit=crop'],
    short_desc: 'Peppery, bright, and packed with micronutrients.',
    long_desc: 'Mix of radish, broccoli, and pea shoots.',
    nutrition: 'Per 50g: 20 kcal',
    storage_tips: 'Keep dry; add just before serving.',
    farm_location: 'Kondapur Pod',
    availability: 'In stock',
    sku: 'UH-MIC-100',
  },
];

export const POSTS = [
  {
    slug: 'hydroponics-basics',
    title: 'Hydroponics 101: How We Grow Without Soil',
    hero_image: 'https://images.unsplash.com/photo-1524594224081-4f3ba2995d65?w=1200&q=80&auto=format&fit=crop',
    excerpt: 'A quick primer on nutrient film technique.',
    body: 'In our vertical farms, plants receive a precisely balanced nutrient solution.',
    author: 'Team UrbanHarvest',
    tags: ['Hydroponics'],
    publish_date: '2025-09-12',
  }
];

export const LOCATIONS = [
  {
    name: 'Hyderabad City Farm',
    type: 'farm',
    address: 'Plot 12, Financial District, Hyderabad',
    hours: 'Daily 9:00–18:00',
    contact: '+91-80000-00000',
    images: ['https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=1200&q=80&auto=format&fit=crop'],
  }
];
